---
title: "R Notebook"
output: html_notebook
---

**Weather Prediction**
**Dataset_source - Kaggle(Mumbai weather dataset)**


```{r}
df = read.csv('weather.csv')
head(df,5)
dim(df)
summary(df)
```

**Splitting the Data from df into train & test**

```{r}
dt = sort(sample(nrow(df), nrow(df)*.7))
    train = df[dt,]
    test =  df[-dt,]
    train
    test
```

**Checking whether there is any null value **

```{r}
    is.null(train)
    is.null(test)
```

**Data for model to train & test**

```{r}
    label_train = train['Relative.Humidity']
    label_test  = test['Relative.Humidity']
    label_test
    label_train
    new_train = subset(train, select = -c(Relative.Humidity) )
    new_test  = subset(test, select = -c(Relative.Humidity) )
    new_train
    new_test
    
```


```{r}
nColor = 2
colors = paletteer_c("scico::berlin", n = 10)

rank = as.factor( as.numeric( cut(df$Relative.Humidity, nColor)))
                   
    plot(
  x = train$Relative.Humidity, 
  y = train$Temperature,
  bg = colors[ rank ],
  cex = 3,
  pch=21
)
     plot(
  x = train$Relative.Humidity, 
  y = train$Wind.Speed,
  bg = colors[ rank ],
  cex = 3,
  pch=21
)
     plot(
  x = train$Relative.Humidity, 
  y = train$Wind.Direction,
  bg = colors[ rank ],
  cex = 3,
  pch=21
)
     
    
```
```{r}
  plot(df["Temperature"][1:10,],type="l") 
  plot(df["Relative.Humidity"][1:10,],type="l")
```
**As the temperature decreases Relative Humidity increases**

```{r}
    plot(train)
```
**MODEL Train & Test**

```{r}
      model = lm(Relative.Humidity ~. , data = train)
      summary(model)
      #predict
      pred = predict(model, test)
      data.frame(pred)
```
```{r}
      #compare predict and actual value
      plot(test$Relative.Humidity, type="l" , lty=1.8, col='red')
      lines(pred , type = "l" , col="blue")
      
      plot(pred, type="l" , lty=1.8, col='blue')
      
      #Accuracy
      rmse = sqrt(mean(pred-df$Relative.Humidity)^2)
      rmse
```








